package ch.xwr.seicentobookit.ui.desktop;

import java.util.Date;

import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Notification;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.xdev.res.ApplicationResource;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPopupDateField;
import com.xdev.ui.XdevView;

import ch.xwr.seicentobookit.business.AdministrationManager;

public class ResetPayDatePopup extends XdevView {

	/**
	 * 
	 */
	public ResetPayDatePopup() {
		super();
		this.initUI();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #btnCancel}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnCancel_buttonClick(Button.ClickEvent event) {
		((Window) this.getParent()).close();					
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #btnCreate}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void btnCreate_buttonClick(Button.ClickEvent event) {
		Date dat = (Date) popupDateField.getConvertedValue();
		
		if (dat != null) {
			AdministrationManager man = new AdministrationManager();
			man.resetBookingDate(dat);
			
			Notification.show("Buchungsdatum zurückgesetzt: " + dat.toString(), Notification.Type.TRAY_NOTIFICATION); 					
			UI.getCurrent().getSession().setAttribute(String.class, "state");
			
			((Window) this.getParent()).close();			
		}
	
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.label2 = new XdevLabel();
		this.label = new XdevLabel();
		this.popupDateField = new XdevPopupDateField();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.btnCreate = new XdevButton();
		this.btnCancel = new XdevButton();
	
		this.label2.setValue("Buchungsdatum zurück setzen.");
		this.label.setValue("Lohndatum per");
		this.popupDateField.setDescription("Admin");
		this.popupDateField.setRequired(true);
		this.btnCreate.setCaption("Zurück setzen");
		this.btnCancel.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/delete1.png"));
		this.btnCancel.setCaption("Abbrechen");
	
		this.btnCreate.setSizeUndefined();
		this.horizontalLayout.addComponent(this.btnCreate);
		this.horizontalLayout.setComponentAlignment(this.btnCreate, Alignment.MIDDLE_CENTER);
		this.btnCancel.setSizeUndefined();
		this.horizontalLayout.addComponent(this.btnCancel);
		this.horizontalLayout.setComponentAlignment(this.btnCancel, Alignment.MIDDLE_CENTER);
		final CustomComponent horizontalLayout_spacer = new CustomComponent();
		horizontalLayout_spacer.setSizeFull();
		this.horizontalLayout.addComponent(horizontalLayout_spacer);
		this.horizontalLayout.setExpandRatio(horizontalLayout_spacer, 1.0F);
		this.gridLayout.setColumns(3);
		this.gridLayout.setRows(4);
		this.label2.setWidth(100, Unit.PERCENTAGE);
		this.label2.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.label2, 0, 0, 1, 0);
		this.label.setSizeUndefined();
		this.gridLayout.addComponent(this.label, 0, 1);
		this.popupDateField.setSizeUndefined();
		this.gridLayout.addComponent(this.popupDateField, 1, 1);
		this.horizontalLayout.setWidth(100, Unit.PERCENTAGE);
		this.horizontalLayout.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.horizontalLayout, 0, 2, 1, 2);
		this.gridLayout.setComponentAlignment(this.horizontalLayout, Alignment.MIDDLE_CENTER);
		final CustomComponent gridLayout_hSpacer = new CustomComponent();
		gridLayout_hSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_hSpacer, 2, 0, 2, 2);
		this.gridLayout.setColumnExpandRatio(2, 1.0F);
		final CustomComponent gridLayout_vSpacer = new CustomComponent();
		gridLayout_vSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_vSpacer, 0, 3, 1, 3);
		this.gridLayout.setRowExpandRatio(3, 1.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setSizeFull();
	
		this.btnCreate.addClickListener(event -> this.btnCreate_buttonClick(event));
		this.btnCancel.addClickListener(event -> this.btnCancel_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel label2, label;
	private XdevButton btnCreate, btnCancel;
	private XdevHorizontalLayout horizontalLayout;
	private XdevPopupDateField popupDateField;
	private XdevGridLayout gridLayout; // </generated-code>


}
