package ch.xwr.seicentobookit.ui.desktop;

import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.UI;
import com.vaadin.ui.Upload;
import com.vaadin.ui.Upload.SucceededEvent;
import com.vaadin.ui.Window;
import com.xdev.dal.DAOs;
import com.xdev.res.ApplicationResource;
import com.xdev.res.StringResourceUtils;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevFieldGroup;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPanel;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevUpload;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.combobox.XdevComboBox;

import ch.xwr.seicentobookit.business.LovState;
import ch.xwr.seicentobookit.business.UploadReceiver;
import ch.xwr.seicentobookit.dal.RowFileDAO;
import ch.xwr.seicentobookit.dal.RowObjectDAO;
import ch.xwr.seicentobookit.entities.RowFile;
import ch.xwr.seicentobookit.entities.RowObject;

public class RowFilePopup extends XdevView {

	/**
	 * 
	 */
	public RowFilePopup() {
		super();
		this.initUI();
		
		//State
		comboBoxState.addItems((Object[])LovState.State.values());
		
		//get Parameter
		Long beanId = (Long) UI.getCurrent().getSession().getAttribute("beanId");
		Long objId = (Long) UI.getCurrent().getSession().getAttribute("objId");
		RowFile bean = null;
		RowObject obj = null;
		
		if (beanId == null) {
			//new
			RowObjectDAO objDao = new RowObjectDAO();
			obj = objDao.find(objId);
						
			bean = new RowFile();
			bean.setRimState(LovState.State.active);
			bean.setRowObject(obj);
			
		} else {
			RowFileDAO dao = new RowFileDAO();
			bean = dao.find(beanId.longValue());
		}
		
		setBeanGui(bean);		
		setupUploader(bean);		
	}

	private void setupUploader(RowFile bean) {
		//uploader
		UploadReceiver rec = new UploadReceiver(bean);
        //upload.setImmediate(true);
        //upload.setButtonCaption("Upload File");
		upload.setReceiver(rec);
		
        upload.addSucceededListener(new Upload.SucceededListener() {
            public void uploadSucceeded(SucceededEvent event) {
                // This method gets called when the upload finished successfully
        	    System.out.println("________________ UPLOAD SUCCEEDED y");
        	    
        	    rec.uploadSucceeded(event);
        	    setBeanGui(rec.getBean());
            }
        });
	}

	private void setBeanGui(RowFile bean) {
		//set Bean + Fields
		fieldGroup.setItemDataSource(bean);
		
		comboBoxObject.setEnabled(false);
		textFieldSize.setEnabled(false);
		textFieldName.setEnabled(false);
		textFieldMime.setEnabled(false);
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdReset}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdReset_buttonClick(Button.ClickEvent event) {
		((Window) this.getParent()).close();					
		
	}

	/**
	 * Event handler delegate method for the {@link XdevButton}
	 * {@link #cmdSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_buttonClick(Button.ClickEvent event) {
		this.fieldGroup.save();
		((Window) this.getParent()).close();					
		
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.panel = new XdevPanel();
		this.form = new XdevGridLayout();
		this.label = new XdevLabel();
		this.comboBoxObject = new XdevComboBox<>();
		this.label2 = new XdevLabel();
		this.textField = new XdevTextField();
		this.label3 = new XdevLabel();
		this.textFieldName = new XdevTextField();
		this.upload = new XdevUpload();
		this.label4 = new XdevLabel();
		this.textFieldMime = new XdevTextField();
		this.textField4 = new XdevTextField();
		this.label6 = new XdevLabel();
		this.textFieldSize = new XdevTextField();
		this.comboBoxState = new XdevComboBox<>();
		this.label5 = new XdevLabel();
		this.label7 = new XdevLabel();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdSave = new XdevButton();
		this.cmdReset = new XdevButton();
		this.fieldGroup = new XdevFieldGroup<>(RowFile.class);
	
		this.label.setValue(StringResourceUtils.optLocalizeString("{$label.value}", this));
		this.comboBoxObject.setTabIndex(1);
		this.comboBoxObject.setContainerDataSource(RowObject.class, DAOs.get(RowObjectDAO.class).findAll());
		this.comboBoxObject.setItemCaptionPropertyId("objAddedBy");
		this.label2.setValue(StringResourceUtils.optLocalizeString("{$label2.value}", this));
		this.textField.setColumns(5);
		this.textField.setTabIndex(2);
		this.label3.setValue(StringResourceUtils.optLocalizeString("{$label3.value}", this));
		this.textFieldName.setTabIndex(3);
		this.upload.setImmediate(true);
		this.label4.setValue(StringResourceUtils.optLocalizeString("{$label4.value}", this));
		this.textFieldMime.setTabIndex(4);
		this.textField4.setColumns(5);
		this.textField4.setTabIndex(5);
		this.label6.setValue(StringResourceUtils.optLocalizeString("{$label6.value}", this));
		this.textFieldSize.setTabIndex(6);
		this.label5.setValue(StringResourceUtils.optLocalizeString("{$label5.value}", this));
		this.label7.setValue(StringResourceUtils.optLocalizeString("{$label7.value}", this));
		this.horizontalLayout.setMargin(new MarginInfo(false));
		this.cmdSave.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/save1.png"));
		this.cmdSave.setCaption(StringResourceUtils.optLocalizeString("{$cmdSave.caption}", this));
		this.cmdSave.setTabIndex(9);
		this.cmdReset.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/delete1.png"));
		this.cmdReset.setCaption(StringResourceUtils.optLocalizeString("{$cmdReset.caption}", this));
		this.fieldGroup.bind(this.comboBoxObject, "rowObject");
		this.fieldGroup.bind(this.textField, "rimNumber");
		this.fieldGroup.bind(this.textFieldName, "rimName");
		this.fieldGroup.bind(this.textFieldMime, "rimMimetype");
		this.fieldGroup.bind(this.textField4, "rimType");
		this.fieldGroup.bind(this.textFieldSize, "rimSize");
		this.fieldGroup.bind(this.comboBoxState, "rimState");
	
		this.cmdSave.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdSave);
		this.horizontalLayout.setComponentAlignment(this.cmdSave, Alignment.MIDDLE_LEFT);
		this.cmdReset.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdReset);
		this.horizontalLayout.setComponentAlignment(this.cmdReset, Alignment.MIDDLE_LEFT);
		this.form.setColumns(3);
		this.form.setRows(9);
		this.label.setSizeUndefined();
		this.form.addComponent(this.label, 0, 0);
		this.comboBoxObject.setWidth(100, Unit.PERCENTAGE);
		this.comboBoxObject.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.comboBoxObject, 1, 0);
		this.label2.setSizeUndefined();
		this.form.addComponent(this.label2, 0, 1);
		this.textField.setSizeUndefined();
		this.form.addComponent(this.textField, 1, 1);
		this.label3.setSizeUndefined();
		this.form.addComponent(this.label3, 0, 2);
		this.textFieldName.setWidth(100, Unit.PERCENTAGE);
		this.textFieldName.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.textFieldName, 1, 2);
		this.upload.setSizeUndefined();
		this.form.addComponent(this.upload, 2, 2);
		this.label4.setSizeUndefined();
		this.form.addComponent(this.label4, 0, 3);
		this.textFieldMime.setWidth(100, Unit.PERCENTAGE);
		this.textFieldMime.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.textFieldMime, 1, 3);
		this.textField4.setSizeUndefined();
		this.form.addComponent(this.textField4, 1, 4);
		this.label6.setSizeUndefined();
		this.form.addComponent(this.label6, 0, 5);
		this.textFieldSize.setWidth(100, Unit.PERCENTAGE);
		this.textFieldSize.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.textFieldSize, 1, 5);
		this.comboBoxState.setSizeUndefined();
		this.form.addComponent(this.comboBoxState, 1, 6);
		this.label5.setSizeUndefined();
		this.form.addComponent(this.label5, 0, 4);
		this.label7.setSizeUndefined();
		this.form.addComponent(this.label7, 0, 6);
		this.horizontalLayout.setSizeUndefined();
		this.form.addComponent(this.horizontalLayout, 1, 7);
		this.form.setComponentAlignment(this.horizontalLayout, Alignment.TOP_RIGHT);
		this.form.setColumnExpandRatio(2, 10.0F);
		final CustomComponent form_vSpacer = new CustomComponent();
		form_vSpacer.setSizeFull();
		this.form.addComponent(form_vSpacer, 0, 8, 2, 8);
		this.form.setRowExpandRatio(8, 1.0F);
		this.form.setSizeFull();
		this.panel.setContent(this.form);
		this.panel.setSizeFull();
		this.setContent(this.panel);
		this.setSizeFull();
	
		this.cmdSave.addClickListener(event -> this.cmdSave_buttonClick(event));
		this.cmdReset.addClickListener(event -> this.cmdReset_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel label, label2, label3, label4, label6, label5, label7;
	private XdevButton cmdSave, cmdReset;
	private XdevUpload upload;
	private XdevHorizontalLayout horizontalLayout;
	private XdevComboBox<?> comboBoxState;
	private XdevFieldGroup<RowFile> fieldGroup;
	private XdevPanel panel;
	private XdevGridLayout form;
	private XdevTextField textField, textFieldName, textFieldMime, textField4, textFieldSize;
	private XdevComboBox<RowObject> comboBoxObject; // </generated-code>


}
