package ch.xwr.seicentobookit.ui.desktop;

import java.util.Collection;
import java.util.Iterator;

import com.vaadin.data.Validator.InvalidValueException;
import com.vaadin.event.ShortcutAction;
import com.vaadin.server.FontAwesome;
import com.vaadin.shared.ui.MarginInfo;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Field;
import com.vaadin.ui.Notification;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevFieldGroup;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevPopupDateField;
import com.xdev.ui.XdevTextField;
import com.xdev.ui.XdevView;
import com.xdev.ui.entitycomponent.combobox.XdevComboBox;
import com.xdev.util.ConverterBuilder;
import ch.xwr.seicentobookit.business.LovState;
import ch.xwr.seicentobookit.business.RowObjectManager;
import ch.xwr.seicentobookit.dal.SalaryBvgBaseDAO;
import ch.xwr.seicentobookit.dal.SalaryBvgBaseLineDAO;
import ch.xwr.seicentobookit.entities.SalaryBvgBase;
import ch.xwr.seicentobookit.entities.SalaryBvgBaseLine;
import ch.xwr.seicentobookit.entities.SalaryBvgBaseLine_;

public class SalaryBvgBaseLinePopup extends XdevView {

	/**
	 * 
	 */
	public SalaryBvgBaseLinePopup() {
		super();
		this.initUI();
		
		this.comboBoxState.addItems((Object[]) LovState.State.values());
		// this.comboBoxWorktype.addItems((Object[])LovState.WorkType.values());

		// get Parameter
		final Long beanId = (Long) UI.getCurrent().getSession().getAttribute("beanId");
		final Long objId = (Long) UI.getCurrent().getSession().getAttribute("objId");
		SalaryBvgBaseLine bean = null;
		SalaryBvgBase obj = null;

		if (beanId == null) {
			// new
			final SalaryBvgBaseDAO objDao = new SalaryBvgBaseDAO();
			obj = objDao.find(objId);

			bean = new SalaryBvgBaseLine();
			bean.setSalaryBvgBasis(obj);
			bean.setSbxState(LovState.State.active);

		} else {
			final SalaryBvgBaseLineDAO dao = new SalaryBvgBaseLineDAO();
			bean = dao.find(beanId.longValue());
		}

		setBeanGui(bean);
		//setROFields();
		
	}

	private void setBeanGui(SalaryBvgBaseLine bean) {
		// set Bean + Fields
		this.fieldGroup.setItemDataSource(bean);
				
	}

	public static Window getPopupWindow() {
		final Window win = new Window();
		win.setWidth("680");
		win.setHeight("380");
		win.center();
		win.setModal(true);
		win.setContent(new SalaryBvgBaseLinePopup());

		return win;
	}
	
	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdSave}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdSave_buttonClick(final Button.ClickEvent event) {
		UI.getCurrent().getSession().setAttribute(String.class, "cmdSave");

		try {
			if (!this.fieldGroup.isValid()){
				final Collection<Field<?>> c2 = this.fieldGroup.getFields();
				for (final Iterator<Field<?>> iterator = c2.iterator(); iterator.hasNext();) {
					final Field<?> object = iterator.next();
					final String name = (String) this.fieldGroup.getPropertyId(object);
					try {
						object.validate();
					} catch (final InvalidValueException e) {
						Notification.show("Ungültiger Wert in Feld " + name, "Message" + e.getMessage(), Notification.Type.ERROR_MESSAGE);
						e.printStackTrace();
					} catch (final Exception e) {
						Notification.show("Fehler beim Speichern " + object.getCaption(), e.getMessage(), Notification.Type.ERROR_MESSAGE);
					}
				}

				return;
			}
			this.fieldGroup.save();

			final RowObjectManager man = new RowObjectManager();
			man.updateObject(this.fieldGroup.getItemDataSource().getBean().getSbxId(),
					this.fieldGroup.getItemDataSource().getBean().getClass().getSimpleName());

			((Window) this.getParent()).close();
			Notification.show("Save clicked", "Daten wurden gespeichert", Notification.Type.TRAY_NOTIFICATION);

		} catch (final Exception e) {
			Notification.show("Fehler beim Speichern", e.getMessage(), Notification.Type.ERROR_MESSAGE);
			e.printStackTrace();
		}
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #cmdClose}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void cmdClose_buttonClick(final Button.ClickEvent event) {
		UI.getCurrent().getSession().setAttribute(String.class, "cmdCancel");
		this.fieldGroup.discard();
		((Window) this.getParent()).close();	
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.form = new XdevGridLayout();
		this.comboBoxState = new XdevComboBox<>();
		this.lblSbxValidFrom = new XdevLabel();
		this.dateSbxValidFrom = new XdevPopupDateField();
		this.lblSbxAgeStartYear = new XdevLabel();
		this.txtSbxAgeStartYear = new XdevTextField();
		this.lblSbxCompany = new XdevLabel();
		this.txtSbxCompany = new XdevTextField();
		this.lblSbxWorker = new XdevLabel();
		this.txtSbxWorker = new XdevTextField();
		this.lblSbxState = new XdevLabel();
		this.horizontalLayout = new XdevHorizontalLayout();
		this.cmdSave = new XdevButton();
		this.cmdClose = new XdevButton();
		this.fieldGroup = new XdevFieldGroup<>(SalaryBvgBaseLine.class);
	
		this.lblSbxValidFrom.setValue("Gültig ab");
		this.dateSbxValidFrom.setTabIndex(2);
		this.lblSbxAgeStartYear.setValue("Alter ab");
		this.txtSbxAgeStartYear.setTabIndex(3);
		this.lblSbxCompany.setValue("Arbeitgeber %");
		this.txtSbxCompany.setConverter(ConverterBuilder.stringToDouble().build());
		this.txtSbxCompany.setTabIndex(4);
		this.lblSbxWorker.setValue("Arbeitnehmer %");
		this.txtSbxWorker.setConverter(ConverterBuilder.stringToDouble().build());
		this.txtSbxWorker.setTabIndex(5);
		this.lblSbxState.setValue("Status");
		this.horizontalLayout.setMargin(new MarginInfo(false));
		this.cmdSave.setIcon(FontAwesome.SAVE);
		this.cmdSave.setCaption("Speichern");
		this.cmdSave.setTabIndex(8);
		this.cmdSave.setClickShortcut(ShortcutAction.KeyCode.ENTER);
		this.cmdClose.setIcon(FontAwesome.CLOSE);
		this.cmdClose.setCaption("Schliessen");
		this.cmdClose.setClickShortcut(ShortcutAction.KeyCode.ESCAPE);
		this.fieldGroup.bind(this.dateSbxValidFrom, SalaryBvgBaseLine_.sbxValidFrom.getName());
		this.fieldGroup.bind(this.txtSbxAgeStartYear, SalaryBvgBaseLine_.sbxAgeStartYear.getName());
		this.fieldGroup.bind(this.txtSbxCompany, SalaryBvgBaseLine_.sbxCompany.getName());
		this.fieldGroup.bind(this.txtSbxWorker, SalaryBvgBaseLine_.sbxWorker.getName());
		this.fieldGroup.bind(this.comboBoxState, SalaryBvgBaseLine_.sbxState.getName());
	
		this.cmdSave.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdSave);
		this.horizontalLayout.setComponentAlignment(this.cmdSave, Alignment.MIDDLE_LEFT);
		this.cmdClose.setSizeUndefined();
		this.horizontalLayout.addComponent(this.cmdClose);
		this.horizontalLayout.setComponentAlignment(this.cmdClose, Alignment.MIDDLE_LEFT);
		this.form.setColumns(2);
		this.form.setRows(7);
		this.comboBoxState.setSizeUndefined();
		this.form.addComponent(this.comboBoxState, 1, 4);
		this.lblSbxValidFrom.setSizeUndefined();
		this.form.addComponent(this.lblSbxValidFrom, 0, 0);
		this.dateSbxValidFrom.setSizeUndefined();
		this.form.addComponent(this.dateSbxValidFrom, 1, 0);
		this.lblSbxAgeStartYear.setSizeUndefined();
		this.form.addComponent(this.lblSbxAgeStartYear, 0, 1);
		this.txtSbxAgeStartYear.setWidth(100, Unit.PERCENTAGE);
		this.txtSbxAgeStartYear.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtSbxAgeStartYear, 1, 1);
		this.lblSbxCompany.setSizeUndefined();
		this.form.addComponent(this.lblSbxCompany, 0, 2);
		this.txtSbxCompany.setWidth(100, Unit.PERCENTAGE);
		this.txtSbxCompany.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtSbxCompany, 1, 2);
		this.lblSbxWorker.setSizeUndefined();
		this.form.addComponent(this.lblSbxWorker, 0, 3);
		this.txtSbxWorker.setWidth(100, Unit.PERCENTAGE);
		this.txtSbxWorker.setHeight(-1, Unit.PIXELS);
		this.form.addComponent(this.txtSbxWorker, 1, 3);
		this.lblSbxState.setSizeUndefined();
		this.form.addComponent(this.lblSbxState, 0, 4);
		this.horizontalLayout.setSizeUndefined();
		this.form.addComponent(this.horizontalLayout, 0, 5, 1, 5);
		this.form.setComponentAlignment(this.horizontalLayout, Alignment.TOP_CENTER);
		this.form.setColumnExpandRatio(1, 100.0F);
		final CustomComponent form_vSpacer = new CustomComponent();
		form_vSpacer.setSizeFull();
		this.form.addComponent(form_vSpacer, 0, 6, 1, 6);
		this.form.setRowExpandRatio(6, 1.0F);
		this.form.setSizeFull();
		this.setContent(this.form);
		this.setSizeFull();
	
		this.cmdSave.addClickListener(event -> this.cmdSave_buttonClick(event));
		this.cmdClose.addClickListener(event -> this.cmdClose_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevFieldGroup<SalaryBvgBaseLine> fieldGroup;
	private XdevLabel lblSbxValidFrom, lblSbxAgeStartYear, lblSbxCompany, lblSbxWorker, lblSbxState;
	private XdevButton cmdSave, cmdClose;
	private XdevHorizontalLayout horizontalLayout;
	private XdevPopupDateField dateSbxValidFrom;
	private XdevComboBox<?> comboBoxState;
	private XdevGridLayout form;
	private XdevTextField txtSbxAgeStartYear, txtSbxCompany, txtSbxWorker;
	// </generated-code>

}
